### ISSUE TITLE
Error "Message: stale element reference"

### ISSUE THREAD

**Issue by jasonjckn** [vkryukov/roam-backup#8] opened 2020-12-29 07:34 UTC
```
Downloading local graph `test123`...Traceback (most recent call last):
  File "/pwnd/_/Downloads/roam_backup.py", line 94, in <module>
    download_local_graph(driver, args.local_graph, args.timeout)
  File "/pwnd/_/Downloads/roam_backup.py", line 33, in download_local_graph
    el.click()
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=87.0.4280.88)
```

**Comment by vkryukov** [comment] 2020-12-29 08:00
Thanks for the report, Jason. Could you please do the following to help me reproduce?

1. Make sure that you have the latest version of Roam when you open your local Roam database ("three dots" menu -> Check for updates), and that you logged, i.e., when you load `https://roamresearch.com/#/offline/test123` it doesn't present you a login window.

2. Launch `python3 --debug roam_backup.py test123 .` - it should launch the Chrome browser in the foreground. What do you observe (e.g., a process is stuck at a certain step, etc.?)

**Comment by vkryukov** [comment] 2021-02-13 21:46
Closing this as the issue is not (consistently) reproducible.

**Closed as completed by vkryukov** 2021-02-13 21:47 UTC
